const TYPES = {
  SET_PRODUCTS_LIST: 'SET_PRODUCTS_LIST',
  ADD_TO_CART: 'ADD_TO_CART',
  DELETE_PRODUCT_FROM_CART: 'DELETE_PRODUCT_FROM_CART',
  DELETE_ALL_FROM_CART: 'DELETE_ALL_FROM_CART',
  CALCULATE_TOTAL_PRICE_OF_THE_CART: 'CALCULATE_TOTAL_PRICE_OF_THE_CART'
}

export default TYPES
